In [2]:
import numpy as np

# Generating Random Arrays

### random.random()

In [19]:
np.random.random(size=(15,4)) 

array([[2.57535643e-01, 2.05239205e-01, 1.23930690e-01, 1.35635977e-01],
       [5.60092705e-01, 8.67850545e-01, 6.00650518e-01, 6.93814693e-01],
       [7.86031041e-01, 8.64595763e-02, 8.60757026e-01, 3.09116839e-01],
       [1.95957522e-01, 8.78029881e-01, 2.50535896e-01, 4.53463139e-01],
       [9.13298754e-01, 9.27511115e-01, 1.67150253e-02, 5.83057784e-01],
       [5.17831704e-03, 6.82509418e-01, 6.28610916e-01, 4.15928179e-01],
       [8.27273126e-01, 8.00960544e-01, 4.48654877e-01, 4.44268807e-01],
       [8.16247454e-02, 9.38673130e-01, 2.67828086e-01, 2.35468801e-01],
       [6.63786637e-01, 7.47137624e-02, 1.95882997e-01, 3.63758735e-01],
       [1.80944011e-02, 6.75892783e-01, 7.03385266e-01, 1.99306579e-01],
       [5.91166421e-01, 5.57084435e-01, 9.55954447e-01, 2.59434433e-02],
       [3.01149415e-01, 5.39442189e-01, 4.32988402e-01, 4.89267052e-01],
       [2.20605907e-01, 1.76576118e-01, 9.09495142e-01, 2.81045437e-01],
       [9.97556136e-01, 7.81973305e-01, 6.24530791e

### random.randint()

In [33]:
np.random.randint(low=10,high=101,size=(19,23))

array([[ 47,  26,  34,  11,  85,  28,  34,  45,  40,  65,  22,  55,  55,
         79,  77,  47,  23,  29,  85,  70,  32,  45,  30],
       [ 43,  27,  27,  75,  30,  20,  32,  89,  58,  33,  20,  19,  21,
        100,  33,  36,  59,  79,  35,  50,  40,  13, 100],
       [ 67,  46,  44,  25,  35,  86,  61,  79,  15,  22,  59,  88,  49,
         77,  47,  83,  49,  76,  34,  81,  76,  70,  35],
       [ 96,  90,  75,  67,  99,  84,  52,  19,  94,  38,  31,  83,  30,
         82,  92,  83,  18,  32,  10,  44,  28,  36,  93],
       [ 16,  44,  44,  70,  71,  58,  45,  96,  98,  31,  80,  80,  84,
         20, 100,  42,  84,  69,  73,  51,  32,  56,  14],
       [ 84,  56,  40,  86,  16,  91,  77,  83,  72,  12,  23,  49,  10,
         10,  56,  44,  88,  19,  82,  78,  93,  69,  69],
       [ 76,  21,  44,  65,  52,  39,  25,  87,  60,  17,  60,  95,  50,
         85,  16,  52,  12,  27,  50,  17,  15,  65,  56],
       [ 32,  40,  60,  66,  52,  25,  62,  33,  77,  63,  21,  33,  70,
   

### random.uniform()

In [45]:
np.random.uniform(low=10.56, high=12.40,size=(10,2))

array([[12.0775624 , 10.85120556],
       [10.68252396, 11.50202066],
       [11.79335082, 11.35067597],
       [10.66765444, 11.97101648],
       [10.90643024, 11.26187096],
       [10.88634681, 11.54319547],
       [12.36651243, 11.92710596],
       [11.43379934, 11.09546033],
       [12.29543984, 11.77687705],
       [11.89515955, 11.75997149]])

### random.choice()

In [67]:
a=np.arange(50)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [58]:
np.random.choice(a,size=(10,20))

array([[42, 21, 24, 49, 35, 17, 46, 41,  1, 39, 36, 49, 35, 32, 18, 11,
        17, 34, 38, 18],
       [23, 35, 20,  4, 43, 21, 14, 29,  1,  3, 24,  8, 23,  3,  6, 47,
         2, 30, 46,  8],
       [39, 30, 38, 46, 43, 13, 38, 21, 16, 47, 16, 38, 29,  7, 39, 17,
         5, 26, 13, 15],
       [18, 40, 19, 17, 17, 48, 11, 32, 39, 30,  2, 44,  6, 19,  5, 46,
         9, 21, 41, 20],
       [36, 33, 49, 21, 10, 33,  2,  5, 46, 26, 41, 12, 21, 20, 16,  0,
         4, 34, 43, 19],
       [23, 41, 42, 41,  3,  7, 36, 45, 14, 15, 21, 25, 36, 29, 10, 49,
        41, 32, 16, 31],
       [ 7, 34, 11, 34,  3, 32, 27, 32, 11, 17, 20, 19, 39, 30, 19,  4,
        34, 36, 35, 46],
       [30, 25, 32, 48, 17, 20, 49, 38, 29, 34, 30, 37, 42, 43, 11, 37,
        42, 18, 36,  1],
       [24,  3, 37, 16, 29, 45, 11, 30, 36,  8,  8, 35, 25, 19, 30, 39,
        20, 36, 36, 20],
       [26, 39, 37, 36,  1, 45, 46, 21, 36, 33, 33, 46,  4, 21, 45, 13,
        46, 14, 32, 48]])

# Shuffling Arrays

### random.shuffle()

In [68]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [66]:
np.random.shuffle(a)
a

array([10,  7, 18,  3, 12, 27, 21, 33, 26,  5, 29, 24, 47,  1, 44, 16, 19,
       30,  6, 23, 42, 37, 48,  4,  8, 41, 49, 35, 36, 34, 39, 14, 45, 31,
       20, 22,  9, 25,  0, 40, 11, 38, 32,  2, 15, 13, 28, 17, 46, 43])

In [79]:
np.random.permutation(a)

array([22,  4, 16,  1, 23, 12,  2, 41, 34, 35, 33,  8, 36, 14, 21, 20, 25,
       40,  7, 30, 44, 10, 27,  9, 24, 26, 39, 49, 37, 47, 17, 31,  6, 43,
       18, 46, 13, 15, 19, 28, 45, 29,  5, 32, 38,  3,  0, 42, 11, 48])

# Generating Standard Normal Distribution

In [91]:
np.random.standard_normal(size=100000).mean()

-0.002264975037345815

In [92]:
np.random.standard_normal(size=100000).std()

0.9958928995863344