# What is NumPy?

NumPy is a low level library written in C \[and Fortran \] for high level mathematical functions. It provides high-performance multidimentional array object, and tools for working with these arrays. NumPy cleverly overcomes the problem of running slower algorithms on Python by using multidimentional arrays and functions that operate on arrays.

In [1]:
import numpy as np

In [4]:
T=(1,2,3,4)
D={1:[1,2,3,4],2:(7,8,9,10)}
np.array(D)

array({1: [1, 2, 3, 4], 2: (7, 8, 9, 10)}, dtype=object)

In [6]:
a=np.array([[1,2,3],[4,5,6]])

# type()

In [7]:
type(a)

numpy.ndarray

In [9]:
type(D)

dict

# shape

In [10]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a.shape

(2, 3)

In [12]:
a=np.array([1,2,3,4])

In [13]:
a.shape

(4,)

In [16]:
L3=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
a3=np.array(L3)
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
a3.shape

(2, 2, 3)

# max()

In [20]:
L=[1,2,3,4]
max(L)

4

In [21]:
a

array([1, 2, 3, 4])

In [22]:
max(a)

4

In [23]:
a.max()

4

In [24]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
max(a3)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [26]:
a3.max()

12

In [27]:
a3.min()

1

# ndim

In [28]:
a.ndim

1

In [29]:
a

array([1, 2, 3, 4])

In [30]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [31]:
a3.ndim

3

In [32]:
a2=np.array([[1],[2],[3]])
a2

array([[1],
       [2],
       [3]])

In [33]:
a2.shape

(3, 1)

In [34]:
a2.ndim

2

In [35]:
sum(L)

10

In [36]:
a.sum()

10

In [37]:
a

array([1, 2, 3, 4])

In [38]:
sum(a)

10

In [40]:
sum(a3)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [41]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
a3.sum()

78

In [43]:
a3.mean()

6.5

In [46]:
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a2.mean(axis=0)

array([2.5, 3.5, 4.5])

In [48]:
a2.mean(axis=1)

array([2., 5.])

In [49]:
a2.sum(axis=0)

array([5, 7, 9])

In [50]:
a2.sum(axis=1)

array([ 6, 15])

# dtype

In [52]:
a3.dtype

dtype('int32')

In [53]:
a4=np.array([1,2,3,4],dtype='float64')

In [54]:
a4

array([1., 2., 3., 4.])

In [55]:
a4.dtype

dtype('float64')

# size

In [56]:
a4.size

4

In [57]:
a4

array([1., 2., 3., 4.])

In [58]:
a3.size

12

In [59]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# itemsize

In [60]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
a3.itemsize

4

In [62]:
a4

array([1., 2., 3., 4.])

In [63]:
a4.itemsize

8

# median()

In [64]:
a4.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [67]:
np.median(a4)

2.5

In [68]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [69]:
np.median(a3)

6.5

In [70]:
np.mean(a3)

6.5