In [1]:
import numpy as np

In [4]:
L=[45,19,35,17,98,53]
L1=[98,78,52,63,55,4]

In [3]:
for i in range(len(L)):
    L[i]+=L1[i]
L

[143, 97, 87, 80, 153, 57]

In [5]:
a=np.array(L)
a1=np.array(L1)

In [6]:
a

array([45, 19, 35, 17, 98, 53])

In [7]:
a1

array([98, 78, 52, 63, 55,  4])

In [8]:
a+a1

array([143,  97,  87,  80, 153,  57])

In [9]:
a=np.arange(24).reshape(4,6)
a1=np.arange(24,48).reshape(4,6)

In [10]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
a1

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47]])

In [12]:
a+a1

array([[24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46],
       [48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70]])

In [13]:
a-a1

array([[-24, -24, -24, -24, -24, -24],
       [-24, -24, -24, -24, -24, -24],
       [-24, -24, -24, -24, -24, -24],
       [-24, -24, -24, -24, -24, -24]])

In [14]:
a*a1

array([[   0,   25,   52,   81,  112,  145],
       [ 180,  217,  256,  297,  340,  385],
       [ 432,  481,  532,  585,  640,  697],
       [ 756,  817,  880,  945, 1012, 1081]])

In [15]:
a/a1

array([[0.        , 0.04      , 0.07692308, 0.11111111, 0.14285714,
        0.17241379],
       [0.2       , 0.22580645, 0.25      , 0.27272727, 0.29411765,
        0.31428571],
       [0.33333333, 0.35135135, 0.36842105, 0.38461538, 0.4       ,
        0.41463415],
       [0.42857143, 0.44186047, 0.45454545, 0.46666667, 0.47826087,
        0.4893617 ]])

In [16]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [17]:
a+1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [18]:
a**2

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256, 289],
       [324, 361, 400, 441, 484, 529]], dtype=int32)

In [19]:
a-2

array([[-2, -1,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]])

In [20]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [21]:
a>15

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [23]:
d=a>15

In [24]:
a[d]

array([16, 17, 18, 19, 20, 21, 22, 23])

In [25]:
a[a>15]

array([16, 17, 18, 19, 20, 21, 22, 23])

In [26]:
a[(a>2) & (a<12)]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [28]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [29]:
a1

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47]])

In [30]:
a1=np.arange(6)

In [31]:
a1

array([0, 1, 2, 3, 4, 5])

In [32]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [33]:
a+a1

array([[ 0,  2,  4,  6,  8, 10],
       [ 6,  8, 10, 12, 14, 16],
       [12, 14, 16, 18, 20, 22],
       [18, 20, 22, 24, 26, 28]])

In [34]:
a=np.arange(100).reshape(25,4)
a1=np.arange(40).reshape(4,10)

In [36]:
a.dot(a1)

array([[ 140,  146,  152,  158,  164,  170,  176,  182,  188,  194],
       [ 380,  402,  424,  446,  468,  490,  512,  534,  556,  578],
       [ 620,  658,  696,  734,  772,  810,  848,  886,  924,  962],
       [ 860,  914,  968, 1022, 1076, 1130, 1184, 1238, 1292, 1346],
       [1100, 1170, 1240, 1310, 1380, 1450, 1520, 1590, 1660, 1730],
       [1340, 1426, 1512, 1598, 1684, 1770, 1856, 1942, 2028, 2114],
       [1580, 1682, 1784, 1886, 1988, 2090, 2192, 2294, 2396, 2498],
       [1820, 1938, 2056, 2174, 2292, 2410, 2528, 2646, 2764, 2882],
       [2060, 2194, 2328, 2462, 2596, 2730, 2864, 2998, 3132, 3266],
       [2300, 2450, 2600, 2750, 2900, 3050, 3200, 3350, 3500, 3650],
       [2540, 2706, 2872, 3038, 3204, 3370, 3536, 3702, 3868, 4034],
       [2780, 2962, 3144, 3326, 3508, 3690, 3872, 4054, 4236, 4418],
       [3020, 3218, 3416, 3614, 3812, 4010, 4208, 4406, 4604, 4802],
       [3260, 3474, 3688, 3902, 4116, 4330, 4544, 4758, 4972, 5186],
       [3500, 3730, 3960, 4190, 44

In [37]:
np.dot(a,a1)

array([[ 140,  146,  152,  158,  164,  170,  176,  182,  188,  194],
       [ 380,  402,  424,  446,  468,  490,  512,  534,  556,  578],
       [ 620,  658,  696,  734,  772,  810,  848,  886,  924,  962],
       [ 860,  914,  968, 1022, 1076, 1130, 1184, 1238, 1292, 1346],
       [1100, 1170, 1240, 1310, 1380, 1450, 1520, 1590, 1660, 1730],
       [1340, 1426, 1512, 1598, 1684, 1770, 1856, 1942, 2028, 2114],
       [1580, 1682, 1784, 1886, 1988, 2090, 2192, 2294, 2396, 2498],
       [1820, 1938, 2056, 2174, 2292, 2410, 2528, 2646, 2764, 2882],
       [2060, 2194, 2328, 2462, 2596, 2730, 2864, 2998, 3132, 3266],
       [2300, 2450, 2600, 2750, 2900, 3050, 3200, 3350, 3500, 3650],
       [2540, 2706, 2872, 3038, 3204, 3370, 3536, 3702, 3868, 4034],
       [2780, 2962, 3144, 3326, 3508, 3690, 3872, 4054, 4236, 4418],
       [3020, 3218, 3416, 3614, 3812, 4010, 4208, 4406, 4604, 4802],
       [3260, 3474, 3688, 3902, 4116, 4330, 4544, 4758, 4972, 5186],
       [3500, 3730, 3960, 4190, 44

In [38]:
a1.dot(a)

ValueError: shapes (4,10) and (25,4) not aligned: 10 (dim 1) != 25 (dim 0)

In [39]:
v=np.arange(10)
v1=np.arange(10,20)

In [40]:
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
v1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [42]:
v.dot(v1)

735

In [43]:
np.dot(v,v1)

735

In [44]:
np.outer(v,v1)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 30,  33,  36,  39,  42,  45,  48,  51,  54,  57],
       [ 40,  44,  48,  52,  56,  60,  64,  68,  72,  76],
       [ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95],
       [ 60,  66,  72,  78,  84,  90,  96, 102, 108, 114],
       [ 70,  77,  84,  91,  98, 105, 112, 119, 126, 133],
       [ 80,  88,  96, 104, 112, 120, 128, 136, 144, 152],
       [ 90,  99, 108, 117, 126, 135, 144, 153, 162, 171]])

In [45]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [46]:
np.transpose(a)

array([[ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60,
        64, 68, 72, 76, 80, 84, 88, 92, 96],
       [ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61,
        65, 69, 73, 77, 81, 85, 89, 93, 97],
       [ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62,
        66, 70, 74, 78, 82, 86, 90, 94, 98],
       [ 3,  7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59, 63,
        67, 71, 75, 79, 83, 87, 91, 95, 99]])

In [47]:
a.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60,
        64, 68, 72, 76, 80, 84, 88, 92, 96],
       [ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61,
        65, 69, 73, 77, 81, 85, 89, 93, 97],
       [ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62,
        66, 70, 74, 78, 82, 86, 90, 94, 98],
       [ 3,  7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59, 63,
        67, 71, 75, 79, 83, 87, 91, 95, 99]])