In [1]:
import numpy as np

In [2]:
a=np.arange(36)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [4]:
a[11]

11

In [8]:
a[-16]

20

In [10]:
a[5:12:2]

array([ 5,  7,  9, 11])

In [12]:
a[-13:-1:3]

array([23, 26, 29, 32])

In [14]:
a[[3,24,21]]

array([ 3, 24, 21])

In [15]:
a1=np.arange(36).reshape(6,6)
a1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [16]:
a1[2,1]

13

In [17]:
a1[0:3,0:2]

array([[ 0,  1],
       [ 6,  7],
       [12, 13]])

In [18]:
a1[3:,4:]

array([[22, 23],
       [28, 29],
       [34, 35]])

In [21]:
a1[-3:,-2:]

array([[22, 23],
       [28, 29],
       [34, 35]])

In [22]:
a1[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [23]:
a1[[1,4,5],2:4]

array([[ 8,  9],
       [26, 27],
       [32, 33]])

In [24]:
a1[[1,3,5],[0,3,4]]

array([ 6, 21, 34])