In [1]:
import numpy as np 

In [2]:
a=np.random.randint(low=10,high=80,size=100)

In [3]:
a

array([38, 31, 13, 73, 77, 74, 19, 56, 38, 22, 77, 44, 58, 43, 21, 28, 31,
       32, 43, 39, 64, 77, 58, 27, 79, 62, 29, 60, 34, 59, 66, 63, 79, 65,
       45, 76, 11, 18, 17, 33, 49, 35, 29, 74, 53, 54, 58, 44, 52, 60, 32,
       50, 60, 36, 20, 56, 31, 68, 36, 17, 64, 53, 36, 13, 73, 48, 14, 77,
       66, 50, 46, 27, 50, 40, 68, 26, 69, 30, 11, 17, 56, 27, 73, 56, 31,
       39, 58, 67, 15, 44, 32, 72, 74, 29, 42, 53, 57, 16, 54, 37])

In [4]:
a.sort()

In [5]:
a

array([11, 11, 13, 13, 14, 15, 16, 17, 17, 17, 18, 19, 20, 21, 22, 26, 27,
       27, 27, 28, 29, 29, 29, 30, 31, 31, 31, 31, 32, 32, 32, 33, 34, 35,
       36, 36, 36, 37, 38, 38, 39, 39, 40, 42, 43, 43, 44, 44, 44, 45, 46,
       48, 49, 50, 50, 50, 52, 53, 53, 53, 54, 54, 56, 56, 56, 56, 57, 58,
       58, 58, 58, 59, 60, 60, 60, 62, 63, 64, 64, 65, 66, 66, 67, 68, 68,
       69, 72, 73, 73, 73, 74, 74, 74, 76, 77, 77, 77, 77, 79, 79])

## argsort()

In [10]:
a1=np.random.randint(low=50,high=1000,size=100)

In [11]:
a1

array([596, 580, 964, 482, 769, 472, 357, 512, 127, 818, 575, 156, 492,
       862,  84, 575, 827, 654, 786, 327, 495, 723, 682, 589, 611, 418,
       196, 223, 799, 302, 299, 117, 298, 960, 467, 110, 678, 452,  70,
       202, 507, 932, 637, 786, 768, 945, 584, 759, 580, 561, 791, 886,
       826, 124, 893, 238, 135, 478, 843, 781, 979, 448, 363, 232, 864,
       856, 999, 926, 309, 110, 977, 357, 123, 674, 296,  57, 543, 160,
       417, 853, 703, 348, 981, 696, 276, 148, 771, 489, 443, 624, 456,
       474, 252, 202, 643, 652, 413,  77, 411, 990])

In [12]:
a1.argsort()

array([75, 38, 97, 14, 35, 69, 31, 72, 53,  8, 56, 85, 11, 77, 26, 93, 39,
       27, 63, 55, 92, 84, 74, 32, 30, 29, 68, 19, 81, 71,  6, 62, 98, 96,
       78, 25, 88, 61, 37, 90, 34,  5, 91, 57,  3, 87, 12, 20, 40,  7, 76,
       49, 15, 10, 48,  1, 46, 23,  0, 24, 89, 42, 94, 95, 17, 73, 36, 22,
       83, 80, 21, 47, 44,  4, 86, 59, 43, 18, 50, 28,  9, 52, 16, 58, 79,
       65, 13, 64, 51, 54, 67, 41, 45, 33,  2, 70, 60, 82, 99, 66],
      dtype=int64)

In [13]:
a1[a1.argsort()]

array([ 57,  70,  77,  84, 110, 110, 117, 123, 124, 127, 135, 148, 156,
       160, 196, 202, 202, 223, 232, 238, 252, 276, 296, 298, 299, 302,
       309, 327, 348, 357, 357, 363, 411, 413, 417, 418, 443, 448, 452,
       456, 467, 472, 474, 478, 482, 489, 492, 495, 507, 512, 543, 561,
       575, 575, 580, 580, 584, 589, 596, 611, 624, 637, 643, 652, 654,
       674, 678, 682, 696, 703, 723, 759, 768, 769, 771, 781, 786, 786,
       791, 799, 818, 826, 827, 843, 853, 856, 862, 864, 886, 893, 926,
       932, 945, 960, 964, 977, 979, 981, 990, 999])

## argmax()

In [14]:
a1

array([596, 580, 964, 482, 769, 472, 357, 512, 127, 818, 575, 156, 492,
       862,  84, 575, 827, 654, 786, 327, 495, 723, 682, 589, 611, 418,
       196, 223, 799, 302, 299, 117, 298, 960, 467, 110, 678, 452,  70,
       202, 507, 932, 637, 786, 768, 945, 584, 759, 580, 561, 791, 886,
       826, 124, 893, 238, 135, 478, 843, 781, 979, 448, 363, 232, 864,
       856, 999, 926, 309, 110, 977, 357, 123, 674, 296,  57, 543, 160,
       417, 853, 703, 348, 981, 696, 276, 148, 771, 489, 443, 624, 456,
       474, 252, 202, 643, 652, 413,  77, 411, 990])

In [16]:
a1[a1.argmax()]

999

## argmin()

In [18]:
a1[a1.argmin()]

57